### ISSUE TITLE
The very first and the very last serial of an interval is not considered

### ISSUE THREAD

**Issue by RezaForoughieh** [jadijadi/sms_serial_verification#10]
The starting serial and the ending serial of an interval is also related to the same product. So in the check_serial function I propose the following change :

  query = f"SELECT * FROM serials WHERE start_serial <= '{serial}' and end_serial >= '{serial}';

**Comment by jadijadi** [comment]
Totally true. This is fixed on PRs. will merge on next video.

**Comment by jadijadi** [comment]
Fixed by https://github.com/jadijadi/sms_serial_verification/pull/9
