### ISSUE TITLE
مشکل آپلود اکسل در ویندوز

### ISSUE THREAD

**Issue by erfansaberi** [jadijadi/sms_serial_verification#101]
سلام، ببینید وقتی یه اکسل آپلود میکنم این ارور رو تو کامند لاین میگیرم
FileNotFoundError: [Errno 2] No such file or directory: '/tmp\\Book1.xlsx'
یعنی برنامه میره دنبال مسیر
/tmp
در حالی که تو ویندوز اصلا همچین پوشه ای نیست

**Comment by mhkarimi1383** [comment]
this app made for Linux environment but you can change them from source code

**Comment by parsampsh** [comment]
برادر من خب این قراره رو سرور لینوکس ران بشه. واسه ویندوز خودت باید اون پوشه رو مسیرشو اصلاح کنی
