### ISSUE TITLE
MySql Syntax problem

### ISSUE THREAD

**Issue by mhkarimi1383** [jadijadi/sms_serial_verification#104]
File "app/main.py", line 391
    cur.execute("INSERT INTO PROCESSED_SMS (status, sender, message, answer, date) VALUES (%s, %s, %s, %s, %s)", (status, sender, message, answer, now))
                                                                                                                                                       ^
IndentationError: unindent does not match any outer indentation level

**Comment by jadijadi** [comment]
آره این رو دیدم. اصلاحش کرده ام در کامپیوتر خودم و فکر کنم پوش هم شده. تشکر
