### ISSUE TITLE
Use a better template

### ISSUE THREAD

**Issue by mhkarimi1383** [jadijadi/sms_serial_verification#13]
I recommend using https://github.com/shoae/material-rtl instead of some hard to use and not fully ready templates and also it's compatible with the Persian Language for future use.
here is the preview: https://shoae.github.io/material-rtl/

**Comment by jadijadi** [comment]
این که الان داریم که به نظرم قشنگه و محیط هم انگلیسی خواهد بود. در نتیجه نیازی به تغییر نیست الان
