### ISSUE TITLE
ReadMe file should contain description about project

### ISSUE THREAD

**Issue by edrisranjbar** [jadijadi/sms_serial_verification#21]
Hi @jadijadi;
Thank you for starting this project. It is not a big deal but I suggest to write a better read me file and explain a little bit about **What is this project**.
this will help others and also make the project look much better I think.
there is some template that we can use like this one:
[PurpleBooth](https://gist.github.com/PurpleBooth/109311bb0361f32d87a2)
It was my personal opinion and I thank you again for sharing this project with open source community.

**Comment by mhkarimi1383** [comment]
solved with https://github.com/jadijadi/sms_serial_verification/pull/34 but waiting for commit the pull request.

**Comment by edrisranjbar** [comment]
Thank you all.
