### ISSUE TITLE
چک کردن باقی مانده بر ده

### ISSUE THREAD

**Issue by SMMousaviSP** [jadijadi/sms_serial_verification#3]
<div dir="rtl">
سلام، خط 74 فایل app.py هنوز هم باقی مانده بر ده رو اشتباه چک میکنه

pull request قبول میکنید برای رفع باگ های مشابه یا بهینه سازی؟
حقیقتش برای بار دوم میخواستم pull request بدم ولی گفتم شاید تصمیم دارید pull request هارو قبول نکنید.
</div>

**Comment by jadijadi** [comment]
بله پول ریکوئست قبول می شه . به شرطی که دقیق باشه و در مورد یک موضوع خاص 
اگر باگ است که کافیه توش بگی باگ چیه و چطوری حل شده (خیلی وقت ها کد کافیه) ولی اگر فیچر است قبلش باید تو ایشو بگی

**Comment by jadijadi** [comment]
fixed in https://github.com/jadijadi/sms_serial_verification/commit/85beb0d0c30595a916b359036ddaf7a3f640c9ee
