### ISSUE TITLE
id 

### ISSUE THREAD

**Issue by aliazani** [jadijadi/sms_serial_verification#55]
سلام جادی جان 
توی خط 41 تا 46
از id 
استفاده شده که توی پایتون 
built-in 
هست به نظرم بهتره عوض شه به یک چیز دگ 
:D

**Comment by mhkarimi1383** [comment]
شما درست میگین ولی داخل پروژه اگه این تغییر ایجاد بشه باید جاهای دیگه هم تغییر کنه که هم دردسر سازه و هم باعث بروز مشکل میشه پایتون خودش اجازه میده که این متغیر توش تغییر ایجاد بشه

**Comment by aliazani** [comment]
نه تا جایی که دیدم فقط مشکل تو همین چند خطه مشکلی ایجاد نمیکنه تغییرش

**Comment by mhkarimi1383** [comment]
توی دیتابیس و به نطرم فایلهای HTML هم استفاده شدن

**Comment by aliazani** [comment]
نمیدونم دقیق اینو ولی توی برنامه اصلی هیچ مشکلی پیش نمیاد به هر حال اینو میزارم باشه جادی خودشم نظر بده

**Comment by aliazani** [comment]
@jadijadi

**Comment by Gr3Kidd3r** [comment]
> سلام جادی جان
> توی خط 41 تا 46
> از id
> استفاده شده که توی پایتون
> built-in
> هست به نظرم بهتره عوض شه به یک چیز دگ
> :D

It's not necessary cause the `id` is in `User` class *namespace* and has no conflicts with the *builtin python* `id` (used for getting identity of something). **Django** too creates an `id` *primary key* in database model classes automatically.

**Comment by aliazani** [comment]
That's true it is not necessary  but in standard programming is better to use another name.

**Comment by Gr3Kidd3r** [comment]
It's a holy war I guess but as mentioned earlier even **Django** use it for model `id Field` so I guess it's not an issue here as it is too common in database related stuff; But personally I agree with you to some degree. :+1:

**Comment by jadijadi** [comment]
سلام سلام. مطمئنا گاهی استفاده می شه منم کردم ولی کار خوبی نیست در نهایت. بهتره نکنیم بخصوص اگر خیلی معنا دار نباشه (:
