### ISSUE TITLE
REMOTE_CALL_API_KEY can be stolen or guessed!

### ISSUE THREAD

**Issue by Gr3Kidd3r** [jadijadi/sms_serial_verification#64]
## The Problem

The endpoint which returns `json` encoded response to external calls is not rate limited so an attacker can *brute-force* the `token` you used. Also the protocol is plain old `HTTP` so if someone sniff the connections can easily steal the `token` on the fly.

### Suggestion
You can give the `API_KEY` to the caller and instruct them to use it for signing and make the endpoint plain and simple and add the rate-limiting decorator used for protecting the login page.
E.g. *Python* has a module called `hmac` (***H**ash based **M**essage **A**uthentication **C**ode*) which you can use like:
```python
import hmac

# Used `$` as a seperator between signature and plain message (some *Django* convention for
# hashing passwords
signature = hmac.new(API_KEY.encode(), msg=message.encode()).hexdigest()
message = f"{message}${signature}"
```
and in the server build the signature again with the same mechanism using `API_KEY` you gave and check if it matches the received signature.

**By implementing this, the `API_KEY` is never in transfer and cannot be stolen and also the rate-limiting mechanism and the self nature of `*HMAC*` it's not practically guessable.** :wink:

**Comment by Gr3Kidd3r** [comment]
If it seems fine to you I can implement the server side checking. :wink:

**Comment by jadijadi** [comment]
بسیار هم ممنون. تو ویدئو هم توضیح دادم الان. hmac خیلی هم خوبه ولی در اینجا کمی کار نفر بعدی روسختتر می کنه. اگر زمانی واقعا اتکی روی این بود ریت لیمیت می کنیم اما حالا به نظرم کار اضافه است... از این نظر که یکی بعدا تو دردسر می افته برای تطابق با من.
