### ISSUE TITLE
You have an error in your SQL syntax on CREATE USER

### ISSUE THREAD

**Issue by ali-sefidmouy** [jadijadi/sms_serial_verification#65]
Hi!
I'm getting this error at the `CREATE USER` line based on your README :
 

> (`CREATE USER 'smsmysql'@'localhost' IDENTIFIED BY 'test' PASSWORD NEVER EXPIRE;`)

**`ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'NEVER EXPIRE' at line 1`**

After I searched this, I found the right way for doing that:

**`ALTER USER 'smsmysql'@'localhost' PASSWORD EXPIRE NEVER`**

Thanks!

**Comment by jadijadi** [comment]
در سیسیتم های مختلف فرق می کنه. می تونم تو داکیومنت اضافه کنم که این فقط یه مثاله و باید با سیستم خودشون چک کنن
