### ISSUE TITLE
receive SMS message with extra text

### ISSUE THREAD

**Issue by maze1377** [jadijadi/sms_serial_verification#66]
Hi 
system doesn't handle SMS like this message

- my code is : AA100

- کد فعال سازی دستگاه من : AA101

-  کد: AB100

- code : B100

i think it's better to handle this type of message for usability system
i can handle this massage by regular expression  if you want

**Comment by jadijadi** [comment]
کار رو سخت نکن (: مساله رو کسی که پروژه داده اونطوری طراحی کرده (:
