### ISSUE TITLE
We can add message texts in config file 

### ISSUE THREAD

**Issue by mhkarimi1383** [jadijadi/sms_serial_verification#68]
I recommend add message texts in config file but I don't done that myself as PR because of it's a little personal.

**Comment by mhkarimi1383** [comment]
I'm working on it and I will do a PR for that

**Comment by jadijadi** [comment]
باید استرینگ ها رو به یه فرمت دیگه بنویسیم چون اون لحظه متغیرها رو نداریم. به نظرم الان به اندازه کافی کارا است و واضح
