### ISSUE TITLE
error message for invalid 

### ISSUE THREAD

**Issue by aliazani** [jadijadi/sms_serial_verification#71]
I'm not sure about it maybe I'am wrong so if another person know about it exactly please help and comment about it.
In line =→ 402:
                    f'Error inserting line {line_number} from serials sheet SERIALS, {e}',
                    'danger')
This is the message and for Valid serial number (Line 368) the message is same so how can we figure out this message is for valid serial or invalid serial
, so I think It's better to be like this :
                    f'Error inserting line {line_number} from serials sheet INVALIDS, {e}',
                    'danger')

**Comment by mhkarimi1383** [comment]
the code is correct both are using try-catch

**Comment by aliazani** [comment]
@mhkarimi1383 Yes the code is correct should we change the sheet name or not?

**Comment by mhkarimi1383** [comment]
no, it's not necessary
